// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw1fup5jzyffUv52OW-8mz5uk9HflKGWM',
    appId: '1:750854265983:web:8425879d42cfe4a7f7734a',
    messagingSenderId: '750854265983',
    projectId: 'auth-firestore-test-fea30',
    authDomain: 'auth-firestore-test-fea30.firebaseapp.com',
    storageBucket: 'auth-firestore-test-fea30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJyaaBDTaewZdd9v18YdOwAtEp3SZuae0',
    appId: '1:750854265983:android:d9a2a2e7e975c7d4f7734a',
    messagingSenderId: '750854265983',
    projectId: 'auth-firestore-test-fea30',
    storageBucket: 'auth-firestore-test-fea30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9w4W0v852BUqXfVxDz3FFtGq1FHMfFK0',
    appId: '1:750854265983:ios:a782f80f6d333281f7734a',
    messagingSenderId: '750854265983',
    projectId: 'auth-firestore-test-fea30',
    storageBucket: 'auth-firestore-test-fea30.appspot.com',
    iosBundleId: 'com.example.flutterAuthFirestoreTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9w4W0v852BUqXfVxDz3FFtGq1FHMfFK0',
    appId: '1:750854265983:ios:3ea07c7cd91c9e37f7734a',
    messagingSenderId: '750854265983',
    projectId: 'auth-firestore-test-fea30',
    storageBucket: 'auth-firestore-test-fea30.appspot.com',
    iosBundleId: 'com.example.flutterAuthFirestoreTest.RunnerTests',
  );
}
